export const DEFAULT_CATEGORIES = [
	{
		id: 'fruit-and-vegetables',
		name: 'Fruit & Vegetables',
		icon: '🍎',
		color: '#22c55e',
		sortOrder: 0,
	},
	{
		id: 'bakery',
		name: 'Bakery',
		icon: '🍞',
		color: '#9c6305',
		sortOrder: 1,
	},
	{
		id: 'meat',
		name: 'Meat',
		icon: '🥩',
		color: '#ef4444',
		sortOrder: 2,
	},
	{
		id: 'dairy-and-eggs',
		name: 'Dairy & Eggs',
		icon: '🧀',
		color: '#debc28',
		sortOrder: 3,
	},
	{
		id: 'frozen',
		name: 'Frozen',
		icon: '🧊',
		color: '#06b6d4',
		sortOrder: 4,
	},
	{
		id: 'spices-and-herbs',
		name: 'Spices & Herbs',
		icon: '🌶️',
		color: '#046116',
		sortOrder: 5,
	},
	{
		id: 'baking-goods',
		name: 'Baking Goods',
		icon: '🧁',
		color: '#d39f03',
		sortOrder: 6,
	},
	{
		id: 'beverages',
		name: 'Beverages',
		icon: '🥤',
		color: '#8b5cf6',
		sortOrder: 7,
	},
	{
		id: 'cans-and-jars',
		name: 'Cans & Jars',
		icon: '🥫',
		color: '#a9b18f',
		sortOrder: 8,
	},
	{
		id: 'snacks-and-sweets',
		name: 'Snacks & Sweets',
		icon: '🍿',
		color: '#ec4899',
		sortOrder: 9,
	},
	{
		id: 'cleaning-and-laundry',
		name: 'Cleaning & Laundry',
		icon: '🧹',
		color: '#64748b',
		sortOrder: 10,
	},
	{
		id: 'personal-care',
		name: 'Personal Care',
		icon: '🧴',
		color: '#14b8a6',
		sortOrder: 11,
	},
	{
		id: 'health',
		name: 'Health',
		icon: '❤️',
		color: '#d946ef',
		sortOrder: 12,
	},
	{
		id: 'other',
		name: 'Other',
		icon: '📦',
		color: '#6b7280',
		sortOrder: 13,
	},
] as const;

export type Category = (typeof DEFAULT_CATEGORIES)[number];
